name: Deploy to Lightsail

on:
  push:
    branches:
      - master  # Or 'main' depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/prism-billing
            git checkout master
            git pull origin master
            npm install
            npx prisma migrate deploy
            npm run build
            pm2 restart prism-billing-api || pm2 start dist/app.js --name prism-billing-api
